# Generated by Django 5.0.14 on 2026-03-07 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extracted_data", models.JSONField(default=dict)),
                ("damage_score", models.FloatField(blank=True, null=True)),
                ("fraud_indicators", models.JSONField(default=list)),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("review", "Manual Review Required"),
                        ],
                        default="review",
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                ("analysis_summary", models.TextField(blank=True)),
                ("pdf_analysis_complete", models.BooleanField(default=False)),
                ("image_analysis_complete", models.BooleanField(default=False)),
                ("analyzed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analysis",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Analysis",
                "verbose_name_plural": "AI Analyses",
            },
        ),
    ]
