# Generated by Django 5.0.14 on 2026-03-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aianalysis",
            name="recommendation",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("review", "Manual Review Required"),
                    ("need_info", "Additional Information Required"),
                ],
                default="review",
                max_length=20,
            ),
        ),
    ]
