# Generated by Django 5.0.14 on 2026-03-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_services", "0002_alter_aianalysis_recommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="aianalysis",
            name="claim_amount_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="aianalysis",
            name="claim_amount_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
